services:
- type: web
  name: platform-hasura
  env: docker
  dockerfilePath: './hasura/Dockerfile'
  dockerContext: './hasura'
  plan: starter
  branch: master
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: platform-prod
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLED_APIS
    value: graphql,metadata
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: SERVERLESS_APOLLO_ENDPOINT
    value: https://packdigital-platform.now.sh/api/v1/graphql
  - key: ENDPOINT_SERVERLESS_APOLLO
    value: https://packdigital-platform.now.sh/api/v1/graphql
  - key: ENDPOINT_IMPORT_SHOPIFY
    value: https://packdigital-platform.now.sh/api/import/shopify

databases:
- name: platform-prod
