services:
- type: web
  name: platform-hasura
  env: docker
  dockerfilePath: './hasura/Dockerfile'
  dockerContext: './hasura'
  plan: starter
  branch: master
  healthCheckPath: /v1/version
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: platform-prod
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLED_APIS
    value: graphql,metadata
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: ENDPOINT_SERVERLESS_APOLLO
    value: https://packdigital-platform.now.sh/api/v1/graphql
  - key: ENDPOINT_SHOPIFY_STARTIMPORT
    value: https://packdigital-platform.now.sh/api/shopify/startImport
  - key: ENDPOINT_QUEUE_SHOPIFY_FETCHPRODUCTS
    value: https://packdigital-platform.now.sh/api/queue/shopify/fetchProducts
  - key: ENDPOINT_QUEUE_SHOPIFY_FETCHPRODUCTVARIANTS
    value: https://packdigital-platform.now.sh/api/queue/shopify/fetchProductVariants

databases:
- name: platform-prod
