services:
- type: web
  name: platform-hasura
  env: docker
  dockerfilePath: './hasura/Dockerfile'
  dockerContext: './hasura'
  plan: starter
  branch: master
  healthCheckPath: /healthz
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: platform-prod
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLED_APIS
    value: graphql,metadata

databases:
- name: platform-prod
