services:
- type: web
  name: hasura
  env: docker
  dockerfilePath: './hasura/Dockerfile'
  dockerContext: './hasura'
  plan: starter
  branch: master
  healthCheckPath: /healthz
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: prod
      property: connectionString

databases:
- name: prod
