version: '3.6'
services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, webhook-log
      HASURA_GRAPHQL_ADMIN_SECRET:
      ENDPOINT_SERVERLESS_APOLLO: http://host.docker.internal:7000/api/v1/graphql
      ENDPOINT_SHOPIFY_STARTIMPORT: http://host.docker.internal:7000/api/shopify/startImport
      ENDPOINT_QUEUE_SHOPIFY_FETCHPRODUCTS: http://host.docker.internal:7000/api/queue/shopify/fetchProducts
      ENDPOINT_QUEUE_SHOPIFY_FETCHPRODUCTVARIANTS: http://host.docker.internal:7000/api/queue/shopify/fetchProductVariants
      ENDPOINT_QUEUE_SHOPIFY_TRANSFORMTOPLATFORM: http://host.docker.internal:7000/api/queue/shopify/transformToPlatform
      ENDPOINT_QUEUE_SHOPIFY_SAVETOPLATFORM: http://host.docker.internal:7000/api/queue/shopify/saveToPlatform
volumes:
  db_data:
